apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent-multi-arch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent-multi-arch
    app.kubernetes.io/part-of: common-nodejs-parent
  name: common-nodejs-parent-multi-arch
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: common-nodejs-parent-multi-arch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: common-nodejs-parent-multi-arch
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/common-nodejs-parent/common-nodejs-parent-multi-arch@sha256:ce4d967f4ba41344ce7e73189bbda6c1f0b8bbc259bc92b9f037495bac412a4b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
